[global]
	e2dsa, e2ts, dedup, z

	shr: /shr
	css-browser: /ui-assets/client-browser-ui.css
    js-browser: /ui-assets/client-browser-ui.js
	th-size: 640x360
	th-crop: fn
	du-who: no
	
    wintitle: Files @ $pub
	name: REDACTED
	doctitle: Files @ --name
	rproxy: 1
	xff-hdr: cf-connecting-ip
	xff-src: lan
	xf-proto-fb: https

[accounts]
	admin: REDACTED

[/]
	/FULL_PATH/copyparty/folders
	accs:
	rwmda: admin

[/ui-assets]
    /FULL_PATH/copyparty/ui-assets
    accs:
        r: *
        rwmda: admin
		
[/clients]
    /FULL_PATH/copyparty/clients
    accs:
        rwmda: admin
    flags:
        zip_who: 3
        ui_nombar
        ui_nonav
        ui_nolbar
        ui_noctxb
        ui_nosrvi
        ui_nocpla
        ui_norepl