[global]
    e2dsa, e2ts, dedup, z

    shr: /shr
    css-browser: /ui-assets/client-browser-ui-v2.0.0.css
    js-browser: /ui-assets/client-browser-ui-v2.0.0.js
    th-size: 640x360
    th-crop: fn
    du-who: no

    wintitle: Files @ $pub
    name: YOUR_NAME
    doctitle: Files @ --name
    rproxy: 1
    xff-hdr: cf-connecting-ip
    xff-src: lan
    xf-proto-fb: https

[accounts]
    admin: CHANGE_ME

[/ui-assets]
    /FULL_PATH/copyparty/ui-assets
    accs:
        r: *
        rwmda: admin

[/]
    /FULL_PATH/copyparty/folders
    accs:
        rwmda: admin

[/share]
    /FULL_PATH/copyparty/share
    accs:
        rwmda: admin
        w: *
    flags:
        lifetime: 2592000
        rotf: %m
        maxb: 128g,1800
